[package]
name = "kine-core"
version = "0.1.0"
edition = "2021"

[features]
tz-system-provider-builtin-iers = []
std = []

[dependencies]
cfg-if.workspace = true

[dev-dependencies]
bolero.workspace = true
