[package]
name = "kine-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []
tz-system-provider-builtin-iers = []
tz-utc-provider-builtin-iers = []

[dependencies]
cfg-if.workspace = true

[dev-dependencies]
bolero.workspace = true
