[package]
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
kine = { workspace = true, features = ["icu"] }
kine-core.workspace = true
#icu_datetime.workspace = true
